//- Setup - Server
#define 	NAME_SERVER 		"Name"
#define 	SERVER_LANGUAGE 	"language"
#define 	SERVER_VERSION 		"your version"
#define 	SERVER_WEBSITE 		"your url"
#define 	SERVER_GM_TEXT 		"Name
#define 	SERVER_COIN 		"Name"
//
#define     OWNER               "Name"
#define     OWNER_TWO           "Name"
//- Setup - Login - Register
#define 	DEFAULT_POS_X 		1111.3097       //you can edit this without any problem
#define 	DEFAULT_POS_Y 		-1797.3878      //you can edit this without any problem
#define 	DEFAULT_POS_Z 		16.5938         //you can edit this without any problem
#define 	DEFAULT_POS_A 		91.7054         //you can edit this without any problem
#define		SECONDS_TO_LOGIN 	30              //you can edit this without any problem
//Setup - Maxs
#define     MAX_BANDS           100             //you can edit this without any problem
